# Generated by Django 5.1.4 on 2024-12-20 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_type', models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], max_length=10)),
                ('fulfillment_date', models.DateField()),
                ('fulfillment_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cupcake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('Vanilla', 'Vanilla'), ('Chocolate', 'Chocolate'), ('French Vanilla', 'French Vanilla'), ('White Chocolate', 'White Chocolate'), ('Double Chocolate', 'Double Chocolate'), ('Strawberry', 'Strawberry'), ('Peanut Butter', 'Peanut Butter'), ('Pumpkin Spice', 'Pumpkin Spice'), ('Blueberry Mint', 'Blueberry Mint'), ('Apple Cinnamon', 'Cookies and Cream'), ('Cookies and Cream', 'Cookies and Cream'), ('Champagne', 'champagne'), ('Chocolate Chip', 'Chocolate Chip'), ('Mississippi Mud', 'Mississippi Mud'), ('Red Velvet', 'Red Velvet'), ('Coconut', 'Coconut')], max_length=50)),
                ('icing_flavor', models.CharField(choices=[('Vanilla', 'Vanilla'), ('Butter Cream', 'Butter Cream'), ('Lemon', 'Lemon'), ('Cream Cheese', 'Cream Cheese'), ('Strawberry', 'Strawberry'), ('Peanut Butter', 'Peanut Butter'), ('Oreo', 'Oreo'), ('Champagne', 'Champagne'), ('Chocolate', 'Chocolate'), ('German Chocolate', 'German Chocolate'), ('Espresso', 'Espresso'), ('Pink Lemonade', 'Pink Lemonade'), ('Cheesecake Maple Bacon', 'Cheesecake Maple Bacon'), ('Dark Chocolate', 'Dark Chocolate'), ('Milk Chocolate', 'Milk Chocolate'), ('Coconut Pecan', 'Coconut Pecan')], max_length=50)),
                ('cupcake_color', models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Green', 'Green'), ('Orange', 'Orange'), ('Yellow', 'Yellow')], max_length=20, null=True)),
                ('icing_color', models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Green', 'Green'), ('Orange', 'Orange'), ('Yellow', 'Yellow')], max_length=20, null=True)),
                ('decorations', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupcakes', to='orders.order')),
            ],
        ),
    ]
